language: ruby
script: "bundle exec rake appraisal:integration"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-19mode
  - jruby-head
  - rbx-2
  - ruby-head
gemfile:
  - gemfiles/actionpack3.2.gemfile
  - gemfiles/actionpack4.0.gemfile
  - gemfiles/actionpack4.1.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/actionpack4.0.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/actionpack4.1.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
